version: '3'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
    expose:
    - "5432"
    networks:
      - mynetwork
    ports:
      - "5432:5432"
  products-info-service:
    environment:
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    build:
      context: .
      dockerfile: Dockerfile-pis
    restart: always
    depends_on:
      - postgres
      - redis
    networks:
      - mynetwork
    ports:
      - "8090:8090"
  create-order-service:
    environment:
      TARGET_URL: "http://products-info-service:8090/quantity"
    build:
      context: .
      dockerfile: Dockerfile-cos
    restart: always
    depends_on:
      - products-info-service
    networks:
      - mynetwork
    ports:
      - "8080:8080"
  redis:
    image: redis:latest
    environment:
      REDIS_PASSWORD: password
    expose:
      - "6379"
    networks:
      - mynetwork
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - mynetwork
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
